name: dartdoc_astro
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

executables:
  dartdoc_astro:

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  dartdoc_json: ^0.4.0
  freezed_annotation: ^2.4.1
  glob: ^2.1.2
  jinja: ^0.5.0
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  lints: ^3.0.0
  test: ^1.24.0
